# Generated by Django 6.0.4 on 2026-04-27 12:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.URLField()),
                ("short_code", models.CharField(max_length=10, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
